"use client";

import React, { useState, useEffect } from "react";
import Image from "next/image";
import Link from "next/link";
import { ExternalLink } from "lucide-react";

const MirrorOfDreamsPage: React.FC = () => {
  const [mounted, setMounted] = useState<boolean>(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  const liveLink = "https://selahmirror.xyz";

  const features = [
    {
      icon: "\u{1F451}",
      title: "Subscription Tiers",
      description:
        "Three tiers designed to meet different reflection needs - Free, Pro, and Unlimited. Each tier unlocks progressively deeper access to AI-powered insights and tracking capabilities.",
    },
    {
      icon: "\u{2728}",
      title: "AI-Powered Reflections",
      description:
        "Personalized insights generated by Claude AI that understand the nuance and depth of your dreams. No generic advice - only recognition of what's already within you.",
    },
    {
      icon: "\u{1F4B3}",
      title: "PayPal Integration",
      description:
        "Secure, seamless payment processing through PayPal subscriptions. Easy to start, easy to manage, and completely transparent pricing.",
    },
    {
      icon: "\u{1F4C8}",
      title: "Evolution Tracking",
      description:
        "Watch your journey unfold over time. Track how your dreams evolve, see patterns in your reflections, and witness your growth across sessions.",
    },
  ];

  const techStack = [
    "Next.js",
    "TypeScript",
    "Claude API",
    "PayPal",
    "Supabase",
    "tRPC",
  ];

  if (!mounted) {
    return (
      <div className="min-h-screen bg-[#0a0f1a] flex items-center justify-center">
        <div className="w-4 h-4 bg-purple-400 rounded-full animate-pulse" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#0a0f1a] text-white relative overflow-hidden">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-[#0a0f1a]/80 backdrop-blur-sm">
        <div className="container-wide">
          <div className="flex items-center justify-between h-16">
            <Link href="/" className="flex items-center space-x-3 group">
              <Image
                src="/logo-symbol.png"
                alt="Ahiya"
                width={28}
                height={28}
                className="transition-transform duration-300 group-hover:scale-105"
              />
              <span className="text-lg font-medium">Ahiya</span>
            </Link>

            <div className="hidden md:flex items-center space-x-8">
              <Link
                href="/#portfolio"
                className="text-slate-300 hover:text-white transition-colors"
              >
                Back to Portfolio
              </Link>
              <a
                href={liveLink}
                target="_blank"
                rel="noopener noreferrer"
                className="gentle-button text-sm px-4 py-2 flex items-center space-x-2"
              >
                <ExternalLink className="w-4 h-4" />
                <span>Visit Live Site</span>
              </a>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="section-breathing pt-32">
        <div className="container-content text-center">
          <div className="animate-fade-in">
            {/* Status Badge */}
            <div className="breathing-glass inline-block px-6 py-3 mb-8">
              <span className="text-emerald-300 font-medium">Live</span>
            </div>

            {/* Large Icon */}
            <div className="text-6xl md:text-8xl mb-8 animate-float">
              {"\u{1FA9E}"}
            </div>

            {/* Title */}
            <h1 className="display-lg spacing-comfortable text-gentle">
              Mirror of Dreams
            </h1>

            {/* Subtitle */}
            <p className="body-xl text-slate-400 spacing-comfortable">
              AI Reflection Tool
            </p>

            {/* Description */}
            <p className="body-lg text-slate-300 max-w-2xl mx-auto spacing-generous leading-relaxed">
              Tiered AI-powered reflection platform with PayPal subscriptions.
              Users explore dreams through 5 sacred questions and receive
              personalized insights. Features subscription tiers
              (Free/Pro/Unlimited) with PayPal payment integration and evolution
              tracking over time.
            </p>

            {/* CTA Button */}
            <div className="spacing-comfortable">
              <a
                href={liveLink}
                target="_blank"
                rel="noopener noreferrer"
                className="gentle-button inline-flex items-center space-x-3 text-lg px-8 py-4"
              >
                <ExternalLink className="w-6 h-6" />
                <span>Visit Live Site</span>
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="section-breathing">
        <div className="container-content">
          <h2 className="heading-xl text-center spacing-generous">
            Key Features
          </h2>

          <div className="grid md:grid-cols-2 gap-8">
            {features.map((feature, index) => (
              <div
                key={feature.title}
                className="animate-fade-in"
                style={{ animationDelay: `${index * 200}ms` }}
              >
                <div className="contemplative-card p-6 md:p-8">
                  <div className="text-3xl md:text-4xl mb-6">{feature.icon}</div>
                  <h3 className="heading-lg mb-4">{feature.title}</h3>
                  <p className="text-slate-300 leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Tech Stack Section */}
      <section className="section-breathing">
        <div className="container-content text-center">
          <h2 className="heading-xl spacing-comfortable">Tech Stack</h2>
          <div className="flex flex-wrap justify-center gap-3">
            {techStack.map((tech) => (
              <span
                key={tech}
                className="px-4 py-2 bg-white/[0.04] border border-white/[0.08] rounded-lg text-slate-300"
              >
                {tech}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="section-breathing">
        <div className="container-narrow text-center">
          <div className="contemplative-card p-8 md:p-12">
            <h2 className="heading-xl spacing-comfortable">Ready to Explore?</h2>
            <p className="body-lg text-slate-300 spacing-comfortable">
              Discover your dreams through AI-powered reflection.
            </p>
            <a
              href={liveLink}
              target="_blank"
              rel="noopener noreferrer"
              className="gentle-button inline-flex items-center space-x-3"
            >
              <ExternalLink className="w-5 h-5" />
              <span>Visit Live Site</span>
            </a>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-16 border-t border-white/5">
        <div className="container-content text-center">
          <div className="flex justify-center mb-6">
            <Image
              src="/logo-symbol.png"
              alt="Ahiya"
              width={24}
              height={24}
              className="opacity-40"
            />
          </div>
          <p className="text-slate-400 text-sm mb-4">
            Made with reverence by <span className="text-gentle">Ahiya</span>
          </p>
          <p className="text-slate-500 text-xs">
            {new Date().getFullYear()} - Building systems that work
          </p>
        </div>
      </footer>
    </div>
  );
};

export default MirrorOfDreamsPage;
